export const DEFAULT_SLOW_RESOURCE_THRESHOLD_MS = 1000;
export const MIN_SLOW_RESOURCE_THRESHOLD_MS = 100;
export const MAX_SLOW_RESOURCE_THRESHOLD_MS = 60_000;
export const REPORT_VERSION = '1.0';
export const REDACTED_VALUE = '[REDACTED]';
